# Generated by Django 6.0.2 on 2026-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Dharmsinh Desai University', max_length=200)),
                ('system_email', models.EmailField(default='assignhub@ddu.ac.in', max_length=254)),
                ('current_academic_year', models.CharField(default='2024-25', max_length=20)),
                ('current_semester', models.CharField(default='Even (Jan-Jun)', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('allowed_formats', models.CharField(default='PDF, DOCX, ZIP', max_length=200)),
                ('allow_late_submissions', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('session_timeout_mins', models.IntegerField(default=60)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('require_2fa', models.BooleanField(default=False)),
            ],
        ),
    ]
