# Generated by Django 6.0.2 on 2026-03-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
