# Generated by Django 6.0.2 on 2026-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_batch_coordinator_batch_semester_course_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
