# Generated by Django 6.0.2 on 2026-03-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='batches', to='academic.course'),
        ),
        migrations.DeleteModel(
            name='FacultyCourseBatchMapping',
        ),
    ]
