# Generated by Django 6.0.2 on 2026-03-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_batch_courses_delete_facultycoursebatchmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
