# Generated by Django 6.0.2 on 2026-03-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_remove_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='coordinator',
        ),
    ]
