# Generated by Django 6.0.2 on 2026-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowed_file_types',
            field=models.CharField(default='all', help_text="Comma separated types, e.g., 'pdf,docx,jpg'", max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_policy',
            field=models.CharField(choices=[('strict', 'Strict Deadline'), ('allow_penalty', 'Allow Late Submissions')], default='allow_penalty', max_length=50),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_file_size_mb',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
