# Generated by Django 6.0.2 on 2026-03-23 12:09

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submission_submissionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(upload_to=assignments.models.submission_file_path),
        ),
    ]
