# Generated by Django 6.0.2 on 2026-03-25 07:49

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_submissionfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattachment',
            name='file',
            field=models.FileField(upload_to=assignments.models.assignment_attachment_path),
        ),
    ]
